# Generated by Django 5.0.4 on 2024-05-15 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='assets/'),
        ),
        migrations.CreateModel(
            name='ChildAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interlinked_assets', models.BooleanField(default=False)),
                ('form_file_fields', models.JSONField(blank=True, default=[{'isParent': None, 'max_files': 1000000, 'name': 'files', 'valid_types': ['image', 'video']}], help_text='Form file fields', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actions', models.ManyToManyField(related_name='project_templates', to='api.action')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.projecttemplate'),
        ),
        migrations.DeleteModel(
            name='ProjectAction',
        ),
    ]
